# Generated by Django 3.2.5 on 2021-10-15 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dsuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='글 내용')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='작성 시간')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsuser.dsuser', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글들',
                'db_table': 'dspost',
            },
        ),
    ]
